kind: pipeline
type: docker
name: default

steps:
    - name: build
      image: docker
      volumes:
          - name: socket
            path: /var/run/docker.sock
      commands:
          - docker build -t inventory .

    - name: deploy
      image: docker
      volumes:
          - name: socket
            path: /var/run/docker.sock
      environment:
          DB_HOST:
              from_secret: DB_HOST
          DB_PORT:
              from_secret: DB_PORT
          DB_NAME:
              from_secret: DB_NAME
          DB_USER:
              from_secret: DB_USER
          DB_PASS:
              from_secret: DB_PASS
          DEVICE:
              from_secret: DEVICE
          STORAGE_HOST:
              from_secret: STORAGE_HOST
          STORAGE_USER:
              from_secret: STORAGE_USER
          STORAGE_PASS:
              from_secret: STORAGE_PASS
          STORAGE_SECURE:
              from_secret: STORAGE_SECURE
          STORAGE_BUCKET:
              from_secret: STORAGE_BUCKET
      commands:
          - docker stop inventory || true
          - docker stop printer || true

          - docker rm inventory || true
          - docker rm printer|| true
          - docker network rm printer || true

          - docker create -e PRINTER_HOST="http://printer:4000" -e DB_HOST=$DB_HOST -e DB_PORT=$DB_PORT -e DB_NAME=$DB_NAME -e DB_USER=$DB_USER -e DB_PASS=$DB_PASS -e STORAGE_HOST=$STORAGE_HOST -e STORAGE_USER=$STORAGE_USER -e STORAGE_PASS=$STORAGE_PASS -e STORAGE_SECURE=$STORAGE_SECURE -e STORAGE_BUCKET=$STORAGE_BUCKET --network postgres --name inventory inventory
          - docker network connect web inventory
          - docker network connect minio inventory
          - docker start inventory

          - docker create -h printer --device /dev/usb/lp0 --name printer --workdir /app/printer inventory uvicorn server:app --port=4000 --host=0.0.0.0
          - docker network create printer
          - docker network connect printer printer
          - docker network connect printer inventory
          - docker start printer
      when:
        branch:
          - master
        event:
          exclude:
            - pull_request

volumes:
    - name: socket
      host:
          path: /var/run/docker.sock
