version: '3'

services:
    db:
        image: postgres:11.1
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
            POSTGRES_DB: testdb
        restart: on-failure
        volumes:
            - ./data/postgres:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        restart: on-failure
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@mtgames.nl
            PGADMIN_DEFAULT_PASSWORD: root
        ports:
            - "5050:80"

    storage:
        image: minio/minio
        ports:
            - "9000:9000"
            - "9001:9001"
        restart: on-failure
        volumes:
            - ./data/minio:/data
        command: server /data --console-address ":9001"
