name: Build and deploy
on:
  push:
    branches:
      - master
      - feature/**
    tags:
      - v*.*.*

jobs:
  build:
    uses: dreaded_x/workflows/.gitea/workflows/docker-kubernetes.yaml@ef78704b98c72e4a6b8340f9bff7b085a7bdd95c
    secrets: inherit
    with:
      upload_manifests: false

  deploy:
    name: Deploy container
    runs-on: ubuntu-latest
    container: catthehacker/ubuntu:act-latest
    needs: build
    if: gitea.ref == 'refs/heads/master'
    steps:
      - name: Stop and remove current container
        run: |
          docker stop inventory || true
          docker rm inventory || true

      - name: Create container
        run: |
          docker create \
            --pull always \
            --restart unless-stopped \
            --name inventory \
            --network postgres \
            -e PRINTER_HOST='${{vars.PRINTER_HOST}}' \
            -e DB_HOST='${{ vars.DB_HOST }}' \
            -e DB_PORT='${{ vars.DB_PORT }}' \
            -e DB_NAME='${{ vars.DB_NAME }}' \
            -e DB_USER='${{ vars.DB_USER }}' \
            -e DB_PASS='${{ secrets.DB_PASS }}' \
            -e STORAGE_HOST='${{ vars.STORAGE_HOST }}' \
            -e STORAGE_USER='${{ vars.STORAGE_USER }}' \
            -e STORAGE_PASS='${{ secrets.STORAGE_PASS }}' \
            -e STORAGE_SECURE='${{ vars.STORAGE_SECURE }}' \
            -e STORAGE_BUCKET='${{ vars.STORAGE_BUCKET }}' \
            $(echo ${{ toJSON(needs.build.outputs.images) }} | jq .server -r)

          docker network connect web inventory
          docker network connect minio inventory

      - name: Start container
        run: docker start inventory
